/**
 * Drizzle schema — Stallion AI Assistant.
 *
 * THE ONE HARD RULE lives partly here: hard facts are typed columns, read
 * through tools, never generated by the model. Every content and conversation
 * row carries `event_id` so nothing can leak across events. The only documented
 * exception is evergreen KB (event_id nullable, tagged by `scope`).
 *
 * Event isolation is enforced by the data layer: the chat path only ever queries
 * the single active event (ACTIVE_EVENT_ID) plus evergreen content — see
 * lib/event/active.ts and lib/kb/retrieve.ts.
 *
 * CONFIDENTIAL BY DESIGN: the `jury` table (and admin credentials) are stored
 * but NEVER read by any chat tool or retrieval query.
 */
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uuid,
  vector,
} from "drizzle-orm/pg-core";

// Embedding dimension is env-driven (default 1536 = OpenAI text-embedding-3-small).
// Falls back to 1536 so `drizzle-kit generate` works without env loaded.
export const EMBEDDING_DIM = Number(process.env.EMBEDDING_DIM ?? 1536);

// ---- Typed JSON shapes (kept in one place; mirrored in lib/types.ts) --------

export type EventFees = Record<string, { amount: number; currency: string; note?: string }>;
export type EventTaxes = Record<
  string,
  { label?: string; rate?: number; amount?: number; currency?: string; note?: string }
>;
export type EventContact = {
  team?: string; // e.g. "Digital Stallion Awards team"
  email?: string;
  phone?: string;
  whatsapp?: string;
  website?: string;
};
export type EligibilityRules = {
  summary?: string;
  requirements?: string[];
  period?: string;
  // Deterministic checks the app can assert on. Only assert eligibility when a
  // rule here confirms it; otherwise treat eligibility as a team decision.
  deterministic?: Record<string, string | number | boolean>;
};
export type ChunkMetadata = {
  documentTitle?: string;
  source?: string;
  chunkIndex?: number;
  [key: string]: unknown;
};

// ---- Events -----------------------------------------------------------------

export const events = pgTable("events", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(), // e.g. INDIA-2027 — matches ACTIVE_EVENT_ID
  name: text("name").notNull(),
  country: text("country").notNull(), // e.g. "IN" | "AE"
  year: integer("year").notNull(),
  editionNumber: integer("edition_number"),
  eventDate: timestamp("event_date", { withTimezone: true }),
  venue: text("venue"),
  eligibilityPeriod: text("eligibility_period"),
  nominationOpen: timestamp("nomination_open", { withTimezone: true }),
  nominationDeadline: timestamp("nomination_deadline", { withTimezone: true }),
  fees: jsonb("fees").$type<EventFees>(),
  taxes: jsonb("taxes").$type<EventTaxes>(),
  contact: jsonb("contact").$type<EventContact>(),
  status: text("status").notNull().default("draft"), // draft | open | closed
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Categories -------------------------------------------------------------

export const categories = pgTable("categories", {
  id: uuid("id").primaryKey().defaultRandom(),
  eventId: uuid("event_id")
    .notNull()
    .references(() => events.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  officialName: text("official_name"),
  description: text("description"),
  eligibilityRules: jsonb("eligibility_rules").$type<EligibilityRules>(),
  clientApprovalRequired: boolean("client_approval_required").notNull().default(false),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Knowledge base ---------------------------------------------------------

export const kbDocuments = pgTable("kb_documents", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Nullable for evergreen docs shared across events.
  eventId: uuid("event_id").references(() => events.id, { onDelete: "cascade" }),
  scope: text("scope").notNull().default("event"), // 'evergreen' | 'event'
  title: text("title").notNull(),
  body: text("body").notNull(),
  source: text("source"),
  approvalStatus: text("approval_status").notNull().default("draft"), // 'draft' | 'approved'
  version: integer("version").notNull().default(1),
  effectiveDate: timestamp("effective_date", { withTimezone: true }),
  expiryDate: timestamp("expiry_date", { withTimezone: true }),
  lastVerified: timestamp("last_verified", { withTimezone: true }),
  active: boolean("active").notNull().default(true),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

export const kbChunks = pgTable(
  "kb_chunks",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => kbDocuments.id, { onDelete: "cascade" }),
    // Nullable for evergreen chunks; retrieval filters on eventId OR scope.
    eventId: uuid("event_id").references(() => events.id, { onDelete: "cascade" }),
    scope: text("scope").notNull().default("event"), // 'evergreen' | 'event'
    content: text("content").notNull(),
    embedding: vector("embedding", { dimensions: EMBEDDING_DIM }).notNull(),
    metadata: jsonb("metadata").$type<ChunkMetadata>(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    // Vector similarity index (HNSW, cosine). The first migration also runs
    // CREATE EXTENSION IF NOT EXISTS vector so this can be created.
    embeddingIdx: index("kb_chunks_embedding_idx").using(
      "hnsw",
      table.embedding.op("vector_cosine_ops"),
    ),
    eventIdx: index("kb_chunks_event_idx").on(table.eventId),
  }),
);

// ---- Forms ------------------------------------------------------------------

export const forms = pgTable("forms", {
  id: uuid("id").primaryKey().defaultRandom(),
  eventId: uuid("event_id")
    .notNull()
    .references(() => events.id, { onDelete: "cascade" }),
  categoryId: uuid("category_id").references(() => categories.id, { onDelete: "set null" }),
  name: text("name").notNull(),
  url: text("url").notNull(),
  active: boolean("active").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Conversations & messages ----------------------------------------------

export const conversations = pgTable("conversations", {
  id: uuid("id").primaryKey().defaultRandom(),
  eventId: uuid("event_id")
    .notNull()
    .references(() => events.id, { onDelete: "cascade" }),
  visitorType: text("visitor_type"), // brand | agency | individual | sponsor | unknown
  status: text("status").notNull().default("open"), // open | handed_off | closed
  summary: text("summary"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

export const messages = pgTable("messages", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id")
    .notNull()
    .references(() => conversations.id, { onDelete: "cascade" }),
  role: text("role").notNull(), // system | user | assistant | tool
  content: text("content").notNull(),
  toolCalls: jsonb("tool_calls").$type<unknown>(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Leads ------------------------------------------------------------------

export const leads = pgTable("leads", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id").references(() => conversations.id, {
    onDelete: "set null",
  }),
  eventId: uuid("event_id")
    .notNull()
    .references(() => events.id, { onDelete: "cascade" }),
  name: text("name"),
  org: text("org"),
  role: text("role"),
  email: text("email"),
  phone: text("phone"),
  visitorType: text("visitor_type"), // brand | agency | individual | sponsor
  approxEntries: integer("approx_entries"),
  categoriesDiscussed: text("categories_discussed").array(),
  purpose: text("purpose"),
  notes: text("notes"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Handoffs ---------------------------------------------------------------

export const handoffs = pgTable("handoffs", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id").references(() => conversations.id, {
    onDelete: "set null",
  }),
  eventId: uuid("event_id")
    .notNull()
    .references(() => events.id, { onDelete: "cascade" }),
  reason: text("reason").notNull(),
  summary: text("summary").notNull(),
  status: text("status").notNull().default("open"), // open | acknowledged | closed
  assignedTo: text("assigned_to"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Unanswered questions ---------------------------------------------------

export const unansweredQuestions = pgTable("unanswered_questions", {
  id: uuid("id").primaryKey().defaultRandom(),
  conversationId: uuid("conversation_id").references(() => conversations.id, {
    onDelete: "set null",
  }),
  eventId: uuid("event_id")
    .notNull()
    .references(() => events.id, { onDelete: "cascade" }),
  question: text("question").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Jury (CONFIDENTIAL — never read by any chat tool) ----------------------

export const jury = pgTable("jury", {
  id: uuid("id").primaryKey().defaultRandom(),
  eventId: uuid("event_id")
    .notNull()
    .references(() => events.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  details: text("details"),
  confidential: boolean("confidential").notNull().default(true),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Admins -----------------------------------------------------------------

export const admins = pgTable("admins", {
  id: uuid("id").primaryKey().defaultRandom(),
  email: text("email").notNull().unique(),
  role: text("role").notNull().default("admin"), // admin | editor | viewer
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
});

// ---- Inferred types ---------------------------------------------------------

export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;
export type Category = typeof categories.$inferSelect;
export type KbDocument = typeof kbDocuments.$inferSelect;
export type KbChunk = typeof kbChunks.$inferSelect;
export type Form = typeof forms.$inferSelect;
export type Conversation = typeof conversations.$inferSelect;
export type Message = typeof messages.$inferSelect;
export type Lead = typeof leads.$inferSelect;
export type Handoff = typeof handoffs.$inferSelect;
export type UnansweredQuestion = typeof unansweredQuestions.$inferSelect;
export type Jury = typeof jury.$inferSelect;
export type Admin = typeof admins.$inferSelect;
